### PR TITLE
Add simpler way of getting claims

### LINKED ISSUE #44: Missing convenient API to get JWT claims
Looks like one has to parse `Yojson.Safe.t` manually to get a value of certain a claim. That does not sound user-friendly at all. I would expect something like `let get_claim: (Jwt.t, string) => option(string)`, maybe along with `let get_claim_json: (Jwt.t, string) => option(Yojson.Safe.t)` for cases when claim value is not a string.

### PR DESCRIPTION
**Pull request by ulrikstrid**
Fixes #44 

Sorry for the delay, does this look like what you would expect @Lupus?

### CODE REVIEW

**Comment by anmonteiro** [comment]
I'd be in favor of having a `Well_known` module with common claims that we'd expect users to get

**Comment by ulrikstrid** [comment]
I think we've had this discussion "offline" är some point. We then said that these should be in other repos. But I wouldn't mind having `Wellknown.oidc : jwt -> oidc_claims` or something.

**Comment by anmonteiro** [comment]
I mean having:

```ocaml
module Well_known = struct
  let sub = "sub"
  ....
end
```

**Comment by Lupus** [comment]
Looks good to me! 👍

**Pull request merged**
